package com.example.mypaint;

import android.content.Context;
import android.graphics.Color;
import android.util.AttributeSet;
import android.view.View;

import androidx.annotation.Nullable;

public class PaintView extends View {

    public static int BRUSH_SIZE = 10;
    public static final int DEFAULT_COLOR = Color.RED;
    public static final int DEFAULT_BG_COLOR = Color.WHITE;
    private static final float TOUCH_TOLERANCE = 4;     // detect when user starts to draw
    private float mX, mY;   // store coordinates of the finger movement
    private Path mPath;


    // Class constructors generated by clicking the class name > Ask (bulb) >
    // 'Create constructor...' option, then select parameters
    public PaintView(Context context) {
        super(context);
    }

    public PaintView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }
}