package com.example.mypaint;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BlurMaskFilter;
import android.graphics.Canvas;
import android.graphics.Color;
//import android.graphics.EmbossMaskFilter;
import android.graphics.MaskFilter;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PointF;
import android.util.AttributeSet;
import android.util.DisplayMetrics;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Toast;

import androidx.annotation.Nullable;

import java.util.ArrayList;

import static android.widget.Toast.*;

public class PaintView extends View {

    public static int BRUSH_SIZE = 10;
    public static final int DEFAULT_COLOR = Color.RED;
    public static final int DEFAULT_BG_COLOR = Color.WHITE;
    private static final float TOUCH_TOLERANCE = 4;     // detect when user starts to draw
    private float mX, mY;   // store coordinates of the finger movement
    private Path mPath;
    private Paint mPaint;
    private ArrayList<FingerPath> paths = new ArrayList(); // Init finger paths array
    private ArrayList<FingerPath> undonePaths = new ArrayList();
    private int currentColor;
    private int backgroundColor = DEFAULT_BG_COLOR;
    private int strokeWidth;
    private boolean emboss;
    private boolean blur;
    //private MaskFilter mEmboss;
    private MaskFilter mBlur;
    private Bitmap mBitmap;
    private Canvas mCanvas;
    private Paint mBitmapPaint = new Paint(Paint.DITHER_FLAG);


    // Class constructors generated by clicking the class name > Ask (bulb) >
    // 'Create constructor...' option, then select parameters
    public PaintView(Context context) {
        //super(context);
        this(context, null);
    }

    public PaintView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        // Brush settings
        mPaint = new Paint();
        mPaint.setAntiAlias(true);
        mPaint.setDither(true);
        mPaint.setColor(DEFAULT_COLOR);
        mPaint.setStyle(Paint.Style.STROKE);
        mPaint.setStrokeJoin(Paint.Join.ROUND);
        mPaint.setStrokeCap(Paint.Cap.ROUND);
        mPaint.setXfermode(null);
        mPaint.setAlpha(0xff);

        // Emboss Mask Filter method has been deprecated since Android 9
        //mEmboss = new EmbossMaskFilter(new float[] {1, 1, 1}, 0.4f, 6, 3.5f);
        mBlur = new BlurMaskFilter(5, BlurMaskFilter.Blur.NORMAL);
    }

    // Initialize the Paint View
    public void init(DisplayMetrics metrics) {
        int height = metrics.heightPixels;
        int width = metrics.widthPixels;

        mBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        mCanvas = new Canvas(mBitmap);

        currentColor = DEFAULT_COLOR;
        strokeWidth = BRUSH_SIZE;
    }

    // Resize the Bitmap and Canvas after orientation change
    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);

        // Create a new bitmap with the new dimensions
        if (w > 0 && h > 0) {
            mBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
            mCanvas = new Canvas(mBitmap);

            // Note: Paths lists are not cleared here. onDraw() will use the new
            // mCanvas and the drawing will be drawn on the new bitmap
        }
    }

    // Method to turn off Emboss and Blur effects
    public void normal() {
        //emboss = false;
        blur = false;
    }

    // Method to turn on Blur effects
    public void blur() {
        blur = true;
    }

    // Method to clear the Paint View
    public void clear() {
        if (paths.size() > 0) {
            backgroundColor = DEFAULT_BG_COLOR;
            paths.clear();
            //normal();
            invalidate();
        } else {
            Toast.makeText(getContext(), "No drawing to clear!", LENGTH_SHORT).show();
        }
    }

    // Method to undo last drawn finger path
    public void undo() {
        if (paths.size() > 0) {
            undonePaths.add(paths.remove(paths.size() - 1));
            invalidate();
        } else {
            Toast.makeText(getContext(),"No drawing to undo!", Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    protected void onDraw(Canvas canvas) {
        //super.onDraw(canvas);
        canvas.save();
        mCanvas.drawColor(backgroundColor);

        for (FingerPath fp : paths) {
            mPaint.setColor(fp.color);
            mPaint.setStrokeWidth(fp.strokeWidth);
            mPaint.setMaskFilter(null);

            if (fp.blur)
                mPaint.setMaskFilter(mBlur);

            mCanvas.drawPath(fp.path, mPaint);
        }

        canvas.drawBitmap(mBitmap, 0, 0, mBitmapPaint);
        canvas.restore();
    }

    private void touchStart(float x, float y) {
        mPath = new Path();
        undonePaths.clear();    // Clear array of undone paths
        FingerPath fp = new FingerPath(currentColor, emboss, blur, strokeWidth, mPath);

        // Capture the starting point coordinates
        fp.points.add(new PointF(x, y));

        paths.add(fp);
        mPath.reset();
        mPath.moveTo(x, y);
        mX = x;
        mY = y;
    }

    private void touchMove(float x, float y) {
        // Call this method while drawing a fingerpath to calculate the distance drawn
        float dx = Math.abs(x - mX);
        float dy = Math.abs(y - mY);

        if (dx >= TOUCH_TOLERANCE || dy >= TOUCH_TOLERANCE) {
            mPath.quadTo(mX, mY, (x + mX) / 2, (y + mY) / 2);

            // Capture the coordinate points during movement
            if (!paths.isEmpty()) {
                paths.get(paths.size() - 1).points.add(new PointF(x, y));
            }

            mX = x;
            mY = y;
        }
    }

    private void touchUp() {
        // Call this method when user lifts their finger at the end of the finger path
        mPath.lineTo(mX, mY);

        // Capture the end coordinate point
        if (!paths.isEmpty()) {
            paths.get(paths.size() - 1).points.add(new PointF(mX, mY));
        }
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        //return super.onTouchEvent(event);
        float x = event.getX();
        float y = event.getY();

        switch(event.getAction()) {
            case MotionEvent.ACTION_DOWN :
                touchStart(x, y);
                //invalidate();
                break;
            case MotionEvent.ACTION_MOVE :
                touchMove(x, y);
                //invalidate();
                break;
            case MotionEvent.ACTION_UP :
                /*touchUp();
                invalidate();
                break;*/
            case MotionEvent.ACTION_CANCEL :
                touchUp();
                //invalidate();
                break;
        }

        // Redraw after the touch event
        invalidate();
        return true;
    }

    public ArrayList<FingerPath> getPaths() {
        return paths;
    }

    public void setPaths(ArrayList<FingerPath> loadedPaths) {
        this.paths = loadedPaths;

        // Create Path objects from the points in the loaded paths
        for (FingerPath fp : paths) {
            fp.path = new Path();
            if (!fp.points.isEmpty()) {
                PointF first = fp.points.get(0);
                fp.path.moveTo(first.x, first.y);

                for (int i = 1; i < fp.points.size(); i++) {
                    PointF p = fp.points.get(i);
                    fp.path.lineTo(p.x, p.y);
                }
            }
        }
        invalidate();   // Refresh the view to show the loaded drawing
    }
}